[listener]
type="socket"

[service.ssh-simulator]
type="ssh-simulator"
credentials=["root:Qwerty123", "root:DIVINE"]

[[port]]
ports=["tcp/8022", "tcp/8023"]
services=["ssh-simulator"]

[service.telnet]
type="telnet"
image="/data/screenshot-20171030174349.png"
server-name="WS-3244"

[[port]]
port="tcp/5900"
services=["telnet"]

[service.ftp]
type="ftp"

[[port]]
port="tcp/21"
services=["ftp"]

[service.dns01]
type="dns"

[[port]]
port="udp/53"
services=["dns01"]

[channel.console]
type="console"

[[filter]]
channel=["console"]

[[logging]]
output = "output.txt"
level = "debug"
